[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bikesmodel"
authors = [{name = "Daniel"}]
dynamic = ["version", "description"]
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "joblib"
]
